export const legalDocuments = {
  terms: {
    eyebrow: 'Terms and conditions',
    title: 'Terms and conditions',
    route: '/terms-and-conditions',
    summary:
      'These terms cover use of the T-Central website, the multiplayer hub, private player worlds, linked identity features, and route portals into game servers and external systems.',
    intro: {
      eyebrow: 'Legal notice',
      title: 'Terms for T-Central services',
      text: 'These terms set expectations for using T-Central web pages, shared community spaces, private player worlds, Steam-linked features, and routes into external systems.',
    },
    metadata: [
      { label: 'Last updated', text: 'June 9, 2026' },
      { label: 'Applies to', text: 'Website, multiplayer hub, private worlds, linked identity, route portals, and voluntary support payments' },
      { label: 'Support channel', text: 'General support, payment questions, conduct reports, access issues, and route questions' },
    ],
    sections: [
      {
        id: 'template-legal-review',
        eyebrow: 'Template/legal review',
        title: 'Draft template notice',
        text: 'These terms are draft template language for planning and transparency. They should be reviewed and approved by qualified legal counsel before production use or reliance.',
      },
      {
        id: 'use-of-service',
        eyebrow: 'Use of service',
        title: 'Use of service',
        text: 'Users are expected to use the site, shared hub, private worlds, and connected route portals responsibly and in accordance with applicable community rules.',
      },
      {
        id: 'community-conduct',
        eyebrow: 'Community conduct',
        title: 'Community conduct',
        text: 'Do not harass, exploit, impersonate, disrupt services, evade moderation, or interfere with another player\'s ability to participate safely in T-Central spaces.',
      },
      {
        id: 'public-private-spaces',
        eyebrow: 'Lobby modes',
        title: 'Public/private spaces',
        text: 'The multiplayer hub is intended as a shared Steam-linked room. Private worlds are intended to remain user-scoped while still allowing server and route access.',
      },
      {
        id: 'external-services',
        eyebrow: 'External services',
        title: 'External services',
        text: 'Route portals, Steam authentication, payment providers, game servers, and community platforms may have separate rules, account requirements, uptime behavior, and privacy practices.',
      },
      {
        id: 'payment-terms',
        eyebrow: 'Payment terms',
        title: 'Payment terms',
        text: 'One-time donations and recurring support are voluntary contributions processed by PayPal. Support does not buy in-game currency, stored value, external payout rights, real-world return, ownership in T-Central, or a paid gameplay advantage.',
      },
      {
        id: 'recurring-support',
        eyebrow: 'Recurring support',
        title: 'Recurring support and cancellation',
        text: 'Monthly support recurs until cancelled through PayPal or the available account-management path. Cancellation stops future recurring billing according to PayPal and account-management timing, but it does not automatically reverse previously completed payments.',
      },
      {
        id: 'refunds-and-support',
        eyebrow: 'Refunds and support',
        title: 'Refund and support handling',
        text: 'Refund, billing, account-linking, and PayPal.Me fallback questions should be sent through the contact path. PayPal.Me fallback may not automatically bind to a Steam-linked account, so supporters should include useful receipt and account details when asking for help.',
      },
      {
        id: 'availability-and-changes',
        eyebrow: 'Availability',
        title: 'Availability and changes',
        text: 'Features, servers, private spaces, route links, and policies may change, pause, or become unavailable as systems are maintained, secured, moderated, or updated.',
      },
      {
        id: 'donations-and-support',
        eyebrow: 'Donations',
        title: 'Voluntary donations and recurring support',
        text: 'Donations and recurring support are voluntary contributions to help maintain T-Central. They are not required for ordinary community participation unless a specific optional support flow states otherwise.',
      },
      {
        id: 'paypal-payments',
        eyebrow: 'PayPal',
        title: 'External PayPal processing',
        text: 'PayPal processes donation and support payments externally. PayPal may require its own account, payment method, terms, privacy notice, dispute process, cancellation tools, and availability controls.',
      },
      {
        id: 'monthly-subscriptions',
        eyebrow: 'Recurring support',
        title: 'Monthly subscriptions and cancellation',
        text: 'Monthly subscriptions recur until canceled through PayPal or through the provided account path where available. Cancellation timing, billing cutoffs, receipts, and failed-payment handling may be controlled by PayPal.',
      },
      {
        id: 'no-guaranteed-benefits',
        eyebrow: 'No stored value',
        title: 'No guaranteed perks, payout, or ownership',
        text: 'Donations do not guarantee perks, currency, payout, stored value, ownership interest, uninterrupted service, or continued access to any specific feature, server, route, recognition, or benefit.',
      },
      {
        id: 'refund-support',
        eyebrow: 'Refunds',
        title: 'Refund and support questions',
        text: 'Refund, billing, receipt, cancellation, or supporter-account questions should be sent through /contact so the T-Central team can review the request and direct you to any applicable PayPal support path.',
      },
    ],
  },
  eula: {
    eyebrow: 'License agreement',
    title: 'End User License Agreement',
    route: '/eula',
    summary: 'This agreement governs your use of the T-Central game, systems, universe structures, and multiplayer hub.',
    sections: [
      {
        id: 'eula-template-review',
        eyebrow: 'Template/legal review',
        title: 'Draft template notice',
        text: 'This EULA is draft template language for planning and transparency. It should be reviewed and approved by qualified legal counsel before production use or reliance.',
      },
      {
        id: 'limited-use',
        eyebrow: 'License scope',
        title: 'Limited use',
        text: 'You are granted a limited, revocable, non-transferable license to access and use T-Central for personal gameplay and related community participation.',
      },
      {
        id: 'no-reverse-engineering',
        eyebrow: 'Restrictions',
        title: 'No reverse engineering',
        text: 'You may not reverse engineer, exploit, duplicate, interfere with, or automate protected game systems, account logic, moderation functions, or multiplayer state systems.',
      },
      {
        id: 'system-ownership',
        eyebrow: 'Ownership',
        title: 'System ownership',
        text: 'All game systems, visuals, route structures, engine logic, and related platform components remain the property of the operator and licensors of T-Central. One-time donations and recurring support are voluntary and do not transfer ownership, intellectual property rights, equity, control, or any real-world return in T-Central.',
      },
      {
        id: 'revocable-supporter-benefits',
        eyebrow: 'Supporter benefits',
        title: 'Revocable supporter benefits',
        text: 'Any supporter recognition, account display, community role, early-access preview, or future supporter perk is a revocable access benefit, not owned property, stored value, in-game currency, external payout rights, or a paid gameplay advantage.',
      },
      {
        id: 'supporter-recognition-and-future-perks',
        eyebrow: 'Support/perks',
        title: 'Supporter recognition and future perks',
        text: 'Any supporter recognition, cosmetic acknowledgement, or future perk is revocable, non-transferable, and not a sale of game ownership, platform ownership, intellectual property, account ownership, or a permanent entitlement.',
      },
      {
        id: 'benefits-remain-governed-by-the-eula',
        eyebrow: 'Service rules',
        title: 'Benefits remain governed by the EULA',
        text: 'In-game items, access, credits, acknowledgements, or benefits remain subject to this EULA, multiplayer policy, moderation decisions, technical availability, and other T-Central service rules.',
      },
    ],
  },
  privacy: {
    eyebrow: 'Privacy policy',
    title: 'Privacy policy',
    route: '/privacy-policy',
    summary:
      'This policy explains the core data used by the T-Central website, Steam-linked sign-in flow, multiplayer hub presence, private world isolation, and connected route portals.',
    intro: {
      eyebrow: 'Legal notice',
      title: 'Privacy at T-Central',
      text: 'This page summarizes how account-linked data, public lobby presence, protected player world state, and off-site routing are handled across the T-Central hub.',
    },
    metadata: [
      { label: 'Last updated', text: 'June 9, 2026' },
      { label: 'Applies to', text: 'Website, Steam sign-in, multiplayer hub, private worlds, route portals, and PayPal-routed support' },
      { label: 'Support channel', text: 'Privacy questions, access requests, payment metadata questions, and removal requests' },
    ],
    sections: [
      {
        id: 'template-legal-review',
        eyebrow: 'Template/legal review',
        title: 'Draft template notice',
        text: 'This privacy policy is draft template language for planning and transparency. It should be reviewed and approved by qualified legal counsel before production use or reliance.',
      },
      {
        id: 'what-we-collect',
        eyebrow: 'Steam sign-in',
        title: 'What we collect',
        text: 'When you sign in with Steam, the system may process your SteamID, display name, profile URL, and avatar for session, lobby, and route-interface purposes.',
      },
      {
        id: 'how-it-is-used',
        eyebrow: 'Multiplayer hub',
        title: 'How it is used',
        text: 'Steam-linked data supports account sessions, shared room presence, flight roles, server routing, moderation context, and continuity between public hub features and protected player spaces.',
      },
      {
        id: 'private-world-data',
        eyebrow: 'Private world',
        title: 'Private world data',
        text: 'Private world state should remain isolated to the linked Steam account. Sensitive private state should be encrypted at rest and transported only over secure sessions.',
      },
      {
        id: 'external-routes',
        eyebrow: 'Route portals',
        title: 'External routes',
        text: 'Connected portals may send you to game servers, Steam-linked authentication surfaces, PayPal payment surfaces, or community systems that operate under their own notices and controls.',
      },
      {
        id: 'payment-routing',
        eyebrow: 'Payment routing',
        title: 'Payment routing and PayPal processing',
        text: 'One-time donations and recurring support are routed to PayPal as the external payment processor. T-Central does not need to collect or store sensitive card, bank, or PayPal credential details handled by PayPal checkout.',
      },
      {
        id: 'receipt-metadata',
        eyebrow: 'Receipt metadata',
        title: 'Account-linked receipt metadata',
        text: 'When support is connected to a Steam-linked account, T-Central may keep account-linked receipt metadata such as package choice, support status, PayPal order or subscription references, timestamps, and fallback notes needed for support, reconciliation, and account display.',
      },
      {
        id: 'payment-provider-routing',
        eyebrow: 'Payment routing',
        title: 'Payment provider routing to PayPal',
        text: 'Donation and support flows may route you away from T-Central to PayPal for external payment processing, account authorization, receipts, recurring billing management, cancellation, and dispute handling.',
      },
      {
        id: 'supporter-metadata',
        eyebrow: 'Supporter records',
        title: 'Steam-linked receipt and account metadata',
        text: 'T-Central may use Steam-linked account identifiers, supporter status, transaction or subscription references, receipt metadata, timestamps, and support notes to track supporter recognition, troubleshoot payments, and prevent duplicate or fraudulent records.',
      },
      {
        id: 'payment-data-limits',
        eyebrow: 'Payment details',
        title: 'No full card or PayPal credential storage',
        text: 'The hub should not store full payment card numbers, security codes, bank credentials, or PayPal login credentials. Those details should be handled by PayPal or other applicable payment providers.',
      },
      {
        id: 'paypal-privacy',
        eyebrow: 'PayPal privacy',
        title: 'PayPal has separate privacy terms',
        text: 'PayPal operates independently and applies its own privacy terms, data collection, retention, security, dispute, fraud-prevention, and account-control practices when you use PayPal support flows.',
      },
      {
        id: 'contact-and-removal-requests',
        eyebrow: 'Support requests',
        title: 'Contact and removal requests',
        text: 'You can contact the T-Central team to ask privacy questions, request review of account-linked records, or request removal where deletion is technically and legally available.',
      },
    ],
  },
  'multiplayer-policy': {
    eyebrow: 'Shared hub policy',
    title: 'Multiplayer policy',
    route: '/multiplayer-policy',
    summary: 'These rules apply when entering the shared hub, interacting with other pilots, and using multiplayer mission systems.',
    sections: [
      {
        id: 'multiplayer-template-review',
        eyebrow: 'Template/legal review',
        title: 'Draft template notice',
        text: 'This multiplayer policy is draft template language for planning and transparency. It should be reviewed and approved by qualified legal counsel before production use or reliance.',
      },
      {
        id: 'respect-shared-play',
        eyebrow: 'Conduct',
        title: 'Respect shared play',
        text: 'Harassment, cheating, griefing, spam, exploit abuse, and disruption of shared play are not allowed in the shared hub.',
      },
      {
        id: 'moderation-rights',
        eyebrow: 'Enforcement',
        title: 'Moderation rights',
        text: 'T-Central may restrict, suspend, or remove shared-hub access when reports, investigation, or system integrity checks indicate abuse or rule violations.',
      },
      {
        id: 'in-game-values-only',
        eyebrow: 'Economy notice',
        title: 'In-game values only',
        text: 'E_s Credits and other in-game yield values are gameplay units only. They are not currency, stored value, external payout rights, or a guarantee of real-world return.',
      },
      {
        id: 'no-paid-gameplay-advantage',
        eyebrow: 'Support fairness',
        title: 'No paid gameplay advantage',
        text: 'One-time donations, recurring support, supporter recognition, account displays, community roles, previews, and future supporter perks do not provide paid gameplay advantage in shared multiplayer play and have no real-world value.',
      },
    ],
  },
};

export const legalDocumentOrder = ['terms', 'eula', 'privacy', 'multiplayer-policy'];
