create table if not exists public.player_accounts (
  account_key text primary key,
  steam_id text not null unique,
  provider text not null default 'steam',
  display_name text not null default 'Steam Pilot',
  profile_url text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_login_at timestamptz not null default now()
);

create table if not exists public.player_account_ledger (
  id bigint generated by default as identity primary key,
  account_key text not null references public.player_accounts(account_key) on delete cascade,
  event_type text not null,
  event_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists player_account_ledger_account_key_created_at_idx
  on public.player_account_ledger (account_key, created_at desc);
